import os from "node:os";
import { dirname, join } from "node:path";
import { enableHook, readInternalHooksState } from "./openclaw-cli.js";
import { GENERATED_HEADER, installOwnedFile, PLUGIN_BASENAME, spawnSnippet } from "./plugin-file.js";
import { hookArgv, PER_TURN_MIN_INTERVAL_SECONDS, type Platform } from "./types.js";

// OpenClaw is the only platform here that needs registration as well as files:
// hasConfiguredInternalHooks() returns false and the entire hook-directory scan
// is skipped unless hooks.internal is configured. We never hand-edit
// openclaw.json (it is JSON5) -- openclaw's own CLI does the write.
const ENABLE_CMD = `openclaw hooks enable ${PLUGIN_BASENAME}`;

// All four are supported on one hook (it registers once per key). Only
// gateway:shutdown has a bounded timeout (5s); the other three are awaited with
// ZERO timeout, which is why the handler must never await the sync.
const EVENTS = ["session:compact:after", "command:reset", "command:stop", "gateway:shutdown"];

function defaultDir(): string {
  // OpenClaw's resolver is HOME ?? USERPROFILE -- no XDG, no APPDATA.
  const stateDir = process.env.OPENCLAW_STATE_DIR;
  if (stateDir) return join(stateDir, "hooks", PLUGIN_BASENAME);
  const configPath = process.env.OPENCLAW_CONFIG_PATH;
  if (configPath) return join(dirname(configPath), "hooks", PLUGIN_BASENAME);
  const home = process.env.HOME || process.env.USERPROFILE || os.homedir();
  return join(home, ".openclaw", "hooks", PLUGIN_BASENAME);
}

// YAML frontmatter whose `metadata` value is itself JSON5. `events` is required:
// an empty array means the hook silently never registers.
function hookMarkdown(): string {
  const meta = JSON.stringify({ openclaw: { emoji: "📊", events: EVENTS } });
  return `---
name: ${PLUGIN_BASENAME}
description: "Sync AI coding token usage to ccusage-hub"
metadata:
  ${meta}
---

Generated by ccusage-hub. Spawns a detached \`ccusage-hub sync\` when a session
compacts, resets, stops, or the gateway shuts down. Safe to delete.
`;
}

function handlerSource(): string {
  // .js, not .ts: no transpiler is wired into openclaw's hooks loader, so TS
  // support would be an assumption. Node is the only runtime (Bun is blocked at
  // launch), so plain ESM is safe. Returning undefined is the safe return -- the
  // dispatcher discards the resolved value and there is no veto protocol.
  return `${GENERATED_HEADER}import { spawn } from "node:child_process"

export default async (event) => {
${spawnSnippet(hookArgv(PER_TURN_MIN_INTERVAL_SECONDS), "  ")}
}
`;
}

// Registration is a config write, so it is gated on the user's existing setting.
function registrationNote(): string {
  const state = readInternalHooksState();
  if (state === "cli-missing") {
    return `; the openclaw CLI was not found, so the hook is NOT active yet -- run \`${ENABLE_CMD}\` to activate it`;
  }
  if (state === "disabled") {
    // Deliberate refusal: enabling would flip a setting the user explicitly
    // turned off, and `openclaw hooks enable` gives no way to opt into only our
    // hook, so this stays the user's call to make.
    return `; NOT activated -- your openclaw config sets hooks.internal.enabled = false and we will not override that. To turn it on yourself run \`${ENABLE_CMD}\` (warning: that re-enables ALL internal hooks, not just ours)`;
  }

  const outcome = enableHook(PLUGIN_BASENAME);
  if (outcome.missing) {
    return `; the openclaw CLI was not found, so the hook is NOT active yet -- run \`${ENABLE_CMD}\` to activate it`;
  }
  if (!outcome.ok) {
    return `; the files are in place but registering failed (${outcome.stderr || "no details given"}) -- run \`${ENABLE_CMD}\` to activate it`;
  }
  // Forwarded even on success: openclaw's config write strips JSON5 comments and
  // says so only on stderr. That warning is the user's sole notice.
  return outcome.stderr ? `; registered (openclaw: ${outcome.stderr})` : "; registered";
}

function installOpenclawHook(settingsPath?: string): string {
  const dir = settingsPath ?? defaultDir();
  // Handler filename must be exactly handler.ts|handler.js|index.ts|index.js.
  const results = [
    installOwnedFile(join(dir, "HOOK.md"), hookMarkdown()),
    installOwnedFile(join(dir, "handler.js"), handlerSource()),
    // Pins handler.js as ESM. Without this, a .js file holding `export default`
    // only loads because Node >=22.7 sniffs module syntax -- verified: with that
    // detection off, the import fails outright. There is no package.json above
    // ~/.openclaw to inherit "type" from, and .mjs is not an accepted handler
    // name, so declaring it in the directory we own is the only stable fix.
    installOwnedFile(join(dir, "package.json"), `{ "type": "module" }\n`),
  ];
  const verb = results.some((r) => r.changed) ? "hook installed" : "hook already installed";

  // Auto-registration runs the real openclaw CLI, which mutates the user's real
  // openclaw.json. An explicit settingsPath means "don't touch my real
  // environment" -- so we honour that for the CLI call too, not just the files,
  // and hand the enable command back instead. Only the default location (or
  // openclaw's own OPENCLAW_STATE_DIR/OPENCLAW_CONFIG_PATH relocation, which are
  // undefined here) auto-registers. This keeps --settings-path fully sandboxing,
  // matching the other four plugin platforms.
  const note =
    settingsPath === undefined
      ? registrationNote()
      : `; registration skipped for a custom path -- run \`${ENABLE_CMD}\` yourself to activate it`;
  return `${verb} (${dir})${note}`;
}

export const openclaw: Platform = {
  id: "openclaw",
  label: "OpenClaw",
  installHook: installOpenclawHook,
};
