import os from "node:os";
import { join } from "node:path";
import { atomicWrite, readIfExists } from "./fs-safe.js";

// Distinctive enough that it cannot collide with a plugin the user wrote, which
// is what lets us treat a file at this path as ours to overwrite.
export const PLUGIN_BASENAME = "ccusage-hub-sync";

export const GENERATED_HEADER =
  "// Generated by ccusage-hub -- do not edit; re-running init overwrites this file.\n" +
  "// Safe to delete: removing it fully uninstalls the auto-sync hook.\n";

// Mirrors xdg-basedir@5.1.0, which several of these agents pin: it has no win32
// branching at all, so on Windows it resolves to %USERPROFILE%\.config -- NOT
// %APPDATA%. Installing to AppData would put the file where the agent never looks.
export function xdgConfigHome(): string {
  return process.env.XDG_CONFIG_HOME || join(os.homedir(), ".config");
}

// The detached-spawn statement embedded in every generated plugin file.
//
// Load-bearing, not style. The sync must never be awaited: pi, openclaw and amp
// await their handlers with no timeout, so awaiting would stall the agent's exit
// for as long as a full usage scan takes. detached+unref lets the child outlive
// the agent; stdio "ignore" keeps it from holding the agent's pipes open;
// windowsHide suppresses a console-window flash.
//
// The win32 branch goes through cmd.exe rather than calling npx.cmd directly:
// since the CVE-2024-27980 hardening (Node 18.20.2+), Node throws EINVAL on any
// attempt to spawn a .bat/.cmd without shell:true. Verified on Node 22.16 --
// the direct call throws, and the catch below would have swallowed it into a
// silent no-op on every Windows install of the Node-hosted agents (pi, openclaw).
// Bun does not enforce that rule, but accepts this form too, so both runtimes
// share one code path. Args stay an argv array (never a shell string), so no
// quoting rules apply and shell:true's injection surface is avoided outright.
export function spawnSnippet(argv: string[], indent: string): string {
  const body = [
    `try {`,
    `  const isWin = process.platform === "win32"`,
    `  const args = ${JSON.stringify(argv)}`,
    `  spawn(isWin ? "cmd.exe" : "npx", isWin ? ["/c", "npx.cmd", ...args] : args, {`,
    `    detached: true,`,
    `    stdio: "ignore",`,
    `    windowsHide: true,`,
    `  }).unref()`,
    `} catch {`,
    `  // Never destabilize the host agent because usage sync could not start.`,
    `}`,
  ];
  return body.map((line) => `${indent}${line}`).join("\n");
}

// `changed` lets a caller append activation steps only when it actually wrote
// the file, without re-parsing its own message string.
export interface OwnedFileResult {
  message: string;
  changed: boolean;
}

// Installs a file that belongs to us. Unlike the user-owned configs there is no
// merge, no backup and no clobber risk, so "already installed" is simply "the
// bytes on disk are already the bytes we would write".
//
// A read failing for any reason other than ENOENT means something unexpected
// occupies the path, and readIfExists throws rather than let us clobber it.
export function installOwnedFile(path: string, content: string): OwnedFileResult {
  if (readIfExists(path) === content) {
    return { message: `hook already installed (${path})`, changed: false };
  }
  atomicWrite(path, content);
  return { message: `hook installed (${path})`, changed: true };
}
